
<script src="http://www.my97.net/dp/My97DatePicker/WdatePicker.js"></script>

<div class="container">
    <div class="navbar-fixed-bottom" style="top:100px;width:50px;height:160px;">
        <button class="btn btn-primary btn-toolbar" data-toggle="modal" data-target="#psModal">
            运<br/>行<br/>中<br/>的<br/>任<br/>务<br/><span class="badge" id='ps_count'></span>
        </button>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            定时任务管理
            <a style="float: right;" href="/cron/create" target="_blank" title="创建定时任务"><span class="glyphicon glyphicon-plus"></span></a>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>时间</th>
                            <th>任务名称</th>
                            <th>状态</th>
                            <th>最后一次执行时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody id="glist">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="modal fade" id="psModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">运行中的任务</h4>
                </div>
                <div class="modal-body">
                    
        <table class="table table-striped table-hover">
            <tbody id="pslist">
            </tbody>
        </table>
                </div>
<!--                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>-->
            </div>
        </div>
    </div>
</div>
<script>
    var $title = $('title').text();
    var logDir = "<?php echo $this->logDir; ?>";
    var logDate = '';

    function log_picked_func(dom) {
        var url = '/' + logDir + '/' + $('#' + dom).val() + '/' + $('#' + dom).attr('log-file') + '.log';
        window.open(url, '_blank');
    }

    function bindlink(dom) {
        WdatePicker({eCont: dom, onpicked: function(dp) {
                alert('你选择的日期是:' + dp.cal.getDateStr())
            }})
    }

    function logLink(logFile, cronId) {
        var link = '<span>';
        link += '<input style="width:1px;border:0px;" log-file="' + logFile + '" id="in_cr_id_' + cronId + '" onfocus="\n\
                    WdatePicker({\n\
                        dateFmt:\'yyyyMMdd\',\n\
                        onpicked:function(dp){\n\
                            log_picked_func(\'in_cr_id_' + cronId + '\')\n\
                        }\n\
                    });\n\
                ">';
        link += '<a onclick="$(\'#in_cr_id_' + cronId + '\').focus();return false;" href="javascript:;" title="日志" class="log">日志</a>';
        link += '</span>';
        return link;
    }
    function cronList($list) {
        if ($.isArray($list)) {
            var tbody = '';
            $.each($list, function(i, item){
                tbody += '<tr class="' + (i % 2 == 0 ? 'odd' : 'even') + '">';
                tbody += '<td>' + item.cronId + '</td>';
                tbody += '<td onclick="alert(this.title);" title="' + item.command + '">' + item.mhdmd + '</td>';
                tbody += '<td>' + item.task + '</td>';
                tbody += '<td>' + (item.active == 1 ? '<span style="color:green;">已激活</span>' : '<span style="color:red;">未激活</span>') + '</td>';
                tbody += '<td>' + item.runAt + '</td>';
                
                var $upLink = '<a href="/cron/create?cronId=' + item.cronId + '" target="_blank" title="修改"><span class="glyphicon glyphicon-pencil"></span></a>';
                var $delLink = '<a href="javascript:;" onclick="if(!confirm(\'确定删除？\')){return false;}deleteItem(' + item.cronId + ');return false;" title="删除"><span class="glyphicon glyphicon-remove"></span></a>';
                var acLab = item.active == 1 ? '失效' : '激活';
                var $activeLink = '<a href="javascript:;" onclick="upActive(' + item.cronId + ', ' + (item.active == 1 ? 0 : 1) + ');return false;" title="' + acLab + '">' + acLab + '</a>';
                
                var $logLink = logLink(item.logFile, item.cronId);
                tbody += '<td>' + $upLink + '&nbsp;' + $delLink + '&nbsp;' + $activeLink + '&nbsp;' + $logLink + '</td>';
                tbody += '</tr>';
            });

            $("#glist").html(tbody);
        }else{
            $("#glist").html('<tr><td colspan="5">没有相关信息</td></tr>');
        }
    }
    function psList($list) {
        var ps_count = 0;
        if ($.isArray($list) && !$.isEmptyObject($list)) {
            var tbody = '';
            $.each($list, function(i, item){
                tbody += '<tr class="' + (i % 2 == 0 ? 'odd' : 'even') + '">';
                var i=0;
                var pid;
                var $inPcloseSets=0;
                $.each(item, function(i, item){
                    if(i === 'pid'){
                        pid=item;
                    }
                    if(i === 'inPcloseSets' && item === 1){
                        $inPcloseSets=1;
                    }
                    if(i > 0){
                        tbody += '<td>' + item + '</td>';
                    }
                });
                if($inPcloseSets===0){
                    tbody += '<td style="width:30px;"><a class="btn btn-danger" href="javascript:;" onclick="pclose(' + pid + ');">关闭该进程</a></td>';
                }else{
                    tbody += '<td style="width:30px;"><a class="btn btn-default disabled" disabled="disabled" href="javascript:;">正在关闭..</a></td>';
                }
                tbody += '</tr>';
                ps_count++;
            });

            $("#pslist").html(tbody);
        }else{
            $("#pslist").html('<tr><td colspan="5">没有相关信息</td></tr>');
        }
        $('#ps_count').html(ps_count);
        if(0 < ps_count){
            $('title').html('(' + ps_count + ')' + $title);
        }else{
            $('title').html($title);
        }
    }
<?php echo 'cronList(' . $this->crons . ');'; ?>;
<?php echo 'psList(' . $this->ps . ');'; ?>;
    
    function reList(){
        $.ajax({
            url: '',
            data: {ajax:'ajax-reList'},
            type: 'POST',
            dataType: 'json',
            success: function(res){
                if(res.code == '1'){
                    window.cronList(res.data);
                    window.psList(res.ps);
                }
            }
        });
    }
    
    function upActive(id, opt){
        $.ajax({
            url: '/cron/active',
            data: {id:id, opt:opt},
            type: 'POST',
            dataType: 'json',
            success: function(res){
                if(res.code == '1'){
                    reList();
                }
            }
        });
    }
    
    function deleteItem(id){
        $.ajax({
            url: '/cron/delete',
            data: {id:id},
            type: 'POST',
            dataType: 'json',
            success: function(res){
                if(res.code == '1'){
                    reList();
                }
            }
        });
    }
    
    function pclose(id){
        if(!confirm('确定关闭（' + id + '）这个进程吗？')){
            return false;
        }
        $.ajax({
            url: '/cron/pclose',
            data: {id:id},
            type: 'POST',
            dataType: 'json',
            success: function(res){
                if(res.code == '1'){
                    reList();
                }
            }
        });
    }
    
    setInterval(function(){reList();}, 10000);
</script>
